name: CI
on:
  pull_request:
    branches: [main]

jobs:
  linting-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: ğŸ›ï¸ checkout
        uses: actions/checkout@v5

      - name: ğŸ“¦ uv
        uses: astral-sh/setup-uv@v4

      - name: ğŸ set up venv
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: ğŸ¦¾ sync
        run: make sync

      - name: ğŸ’… linting
        run: make linting

      - name: ğŸ§ª test
        run: make test

      - name: ğŸ“¦ requirements
        run: make export
